version: "2.0"
services:
  api:
    container_name: nest_api
    build: .
    volumes:
      - .:/home/api
      - /home/api/node_modules
    ports:
      - "3333:3333"
  database:
    image: postgres
    container_name: nest_db
    environment:
      POSTGRES_DB: nest_api
      POSTGRES_PASSWORD: root
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
